name: Deploy Model

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      # Variables generales de la API
      MODEL_NAME: ${{ vars.MODEL_NAME }}
      MODEL_ALIAS: ${{ vars.MODEL_ALIAS }}
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}
      AZURE_CONTAINER_NAME: ${{ vars.AZURE_CONTAINER_NAME }}
      AZURE_REGION: ${{ vars.AZURE_REGION }}
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      - name: Set MODEL_URI
        run: |
          echo "MODEL_URI=models:/${{ env.MODEL_NAME }}@${{ env.MODEL_ALIAS }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }} ./deployment

      - name: Push Docker image
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}

      - name: Deploy to Azure Container Instances
        run: |
          az container create \
            --name ${{ env.AZURE_CONTAINER_NAME }} \
            --image ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --registry-login-server ${{ secrets.ACR_NAME }}.azurecr.io \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.ACR_PASSWORD }} \
            --dns-name-label ${{ env.AZURE_CONTAINER_NAME }}-${{ github.run_id }} \
            --environment-variables \
              MODEL_URI=${{ env.MODEL_URI }} \
              MLFLOW_TRACKING_URI=${{ vars.MLFLOW_URL }} \
              AZURE_STORAGE_CONNECTION_STRING=$AZURE_STORAGE_CONNECTION_STRING \
            --ports 8080 \
            --os-type Linux \
            --cpu 1 \
            --memory 2.0 \
            --location ${{ env.AZURE_REGION }}
      
      - name: Wait and probe API
        run: |
          sleep 90
          curl --fail http://$AZURE_CONTAINER_NAME-${{ github.run_id }}.${{ env.AZURE_REGION }}.azurecontainer.io:8080/health
          
